name: Portfolio CI/CD to VPC

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install & Build React app
      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # 4. Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build & push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-portfolio-image:latest

      # 6. Deploy inside VPC host
      - name: Deploy to VPC Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPC_HOST }}       # your VPC server IP
          username: ${{ secrets.VPC_USER }}   # e.g., ec2-user / ubuntu
          key: ${{ secrets.VPC_SSH_KEY }}     # private key stored in GitHub secrets
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-portfolio-image:latest
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --name portfolio -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/my-portfolio-image:latest
